/**
 * The sound effects (how they were made: docs/sfx.md). Pure data and name matching, with no
 * browser or Vite APIs, so a Node script can read it as well as the game. The files
 * themselves are found in files.ts.
 */

/** The one-shot effects. */
export const SOUND_IDS = [
  'cannon',
  'hull-hit',
  'splash',
  'sail-tear',
  'barrel-blast',
  'sinking',
  'sails-set',
  'step-sand',
  'step-grass',
  'step-wood',
  'step-stone',
  'axe-chop',
  'tree-fall',
  'pickaxe',
  'outcrop-break',
  'dig',
  'chest-found',
  'pickup',
  'pistol',
  'rifle',
  'musket',
  'reload',
  'bullet-hit',
  'goat',
  'boar',
  'bandit-shout',
  'captain-hurt',
  'blade-clash',
  'parry',
  'block',
  'kick',
  'swing',
  'grunt',
  'guardian-wail',
  'saw',
  'forge-hammer',
  'click',
  'coins',
  'page',
  'cant',
] as const;
export type SoundId = (typeof SOUND_IDS)[number];

/** The ambience loops, crossfaded by where the captain is and what is happening. */
export const LOOP_IDS = ['waves', 'timbers', 'rigging', 'surf', 'gulls', 'harbour', 'campfire'] as const;
export type LoopId = (typeof LOOP_IDS)[number];

export type SfxName = SoundId | LoopId;

export interface SoundSpec {
  /** What to ask ElevenLabs for. */
  prompt: string;
  /** How long to generate (ElevenLabs takes 0.5 to 30). */
  seconds: number;
  /** How many variants to generate. */
  takes: number;
  /** Gain, tuned by ear. */
  volume: number;
  /** World units from the camera's focus at which it fades to nothing; 0 is heard everywhere, centred. */
  reach: number;
  /** Most that may sound at once, per group, or per id when there is no group. */
  cap: number;
  group?: string;
  /** The random pitch shift, plus or minus this fraction. */
  pitch: number;
  loop?: true;
}

export const SOUNDS: Record<SfxName, SoundSpec> = {
  cannon: {
    prompt: 'A single 18th-century naval cannon firing from a wooden warship: a deep, heavy boom with a sharp crack and a rolling rumble tail over open sea. No music.',
    seconds: 2.5,
    takes: 3,
    volume: 1.6,
    reach: 320,
    cap: 8,
    pitch: 0.06,
  },
  'hull-hit': {
    prompt: 'A cannonball smashing into a wooden ship\'s hull: a heavy splintering crack of oak planks with debris clattering. No music.',
    seconds: 1.5,
    takes: 3,
    volume: 1,
    reach: 220,
    cap: 4,
    pitch: 0.08,
  },
  splash: {
    prompt: 'A cannonball plunging into the sea close by: a deep heavy water splash with spray falling back. No music.',
    seconds: 1.5,
    takes: 3,
    volume: 0.65,
    reach: 220,
    cap: 4,
    pitch: 0.1,
  },
  'sail-tear': {
    prompt: 'Chain shot ripping through a ship\'s canvas sails and rigging: a loud tearing of heavy cloth and snapping ropes. No music.',
    seconds: 1.5,
    takes: 2,
    volume: 1,
    reach: 200,
    cap: 2,
    pitch: 0.08,
  },
  'barrel-blast': {
    prompt: 'A floating barrel of gunpowder exploding at sea: a big muffled blast, a burst of water and wooden debris raining down. No music.',
    seconds: 3,
    takes: 2,
    volume: 1,
    reach: 320,
    cap: 3,
    pitch: 0.05,
  },
  sinking: {
    prompt: 'A wooden sailing ship sinking: deep groaning timbers, rushing water flooding the hull, bubbling and a final gurgle. No music.',
    seconds: 6,
    takes: 1,
    volume: 1,
    reach: 320,
    cap: 2,
    pitch: 0.03,
  },
  'sails-set': {
    prompt: 'Sailors setting the sails on a wooden ship: heavy canvas unfurling and snapping full of wind, ropes running through blocks. No music.',
    seconds: 2,
    takes: 2,
    volume: 1,
    reach: 80,
    cap: 1,
    pitch: 0.05,
  },
  'step-sand': {
    prompt: 'A single footstep of a boot on soft dry beach sand, close up. One step only.',
    seconds: 0.6,
    takes: 3,
    volume: 1,
    reach: 30,
    cap: 2,
    group: 'step',
    pitch: 0.1,
  },
  'step-grass': {
    prompt: 'A single footstep of a leather boot on grass and soft earth, close up. One step only.',
    seconds: 0.6,
    takes: 3,
    volume: 1,
    reach: 30,
    cap: 2,
    group: 'step',
    pitch: 0.1,
  },
  'step-wood': {
    prompt: 'A single footstep of a heavy boot on old wooden planks, a hollow knock, close up. One step only.',
    seconds: 0.6,
    takes: 3,
    volume: 1,
    reach: 30,
    cap: 2,
    group: 'step',
    pitch: 0.1,
  },
  'step-stone': {
    prompt: 'A single footstep of a boot on stone and gravel, a crunchy scuff, close up. One step only.',
    seconds: 0.6,
    takes: 3,
    volume: 1,
    reach: 30,
    cap: 2,
    group: 'step',
    pitch: 0.1,
  },
  'axe-chop': {
    prompt: 'A single axe blow biting into a tree trunk: a solid woody chop. One chop only. No music.',
    seconds: 0.8,
    takes: 3,
    volume: 1,
    reach: 45,
    cap: 4,
    pitch: 0.08,
  },
  'tree-fall': {
    prompt: 'A palm tree cracking and crashing to the ground: splitting wood, rustling leaves, a heavy thud. No music.',
    seconds: 3.5,
    takes: 2,
    volume: 1,
    reach: 70,
    cap: 2,
    pitch: 0.05,
  },
  pickaxe: {
    prompt: 'A single iron pickaxe strike on hard rock: a sharp metallic clink and a few chips of stone. One strike only.',
    seconds: 0.8,
    takes: 3,
    volume: 1,
    reach: 45,
    cap: 4,
    pitch: 0.08,
  },
  'outcrop-break': {
    prompt: 'A rock outcrop breaking apart: stone cracking and chunks of rock tumbling to the ground. No music.',
    seconds: 1.5,
    takes: 2,
    volume: 1,
    reach: 55,
    cap: 2,
    pitch: 0.06,
  },
  dig: {
    prompt: 'A single shovel scoop into sandy earth: a dry scrape and the soil tipped aside. One scoop only.',
    seconds: 0.8,
    takes: 3,
    volume: 1,
    reach: 30,
    cap: 3,
    pitch: 0.1,
  },
  'chest-found': {
    prompt: 'A spade striking a buried wooden treasure chest, then the lid creaking open over a jingle of gold coins. No music.',
    seconds: 2.5,
    takes: 1,
    volume: 1,
    reach: 40,
    cap: 1,
    pitch: 0.03,
  },
  pickup: {
    prompt: 'A small soft pickup sound: an item scooped up into a leather satchel. Short and quiet.',
    seconds: 0.5,
    takes: 2,
    volume: 1,
    reach: 0,
    cap: 2,
    pitch: 0.08,
  },
  pistol: {
    prompt: 'A single 18th-century flintlock pistol shot: the flint snap, a sharp bang and a puff of smoke. No music.',
    seconds: 1.5,
    takes: 2,
    volume: 1,
    reach: 90,
    cap: 3,
    pitch: 0.06,
  },
  rifle: {
    prompt: 'A single long flintlock rifle shot: a flint snap and a loud cracking report echoing off hills. No music.',
    seconds: 2,
    takes: 2,
    volume: 1,
    reach: 110,
    cap: 3,
    pitch: 0.05,
  },
  musket: {
    prompt: 'A single distant flintlock musket shot fired by a bandit: a dull boom with a short echo. No music.',
    seconds: 2,
    takes: 3,
    volume: 1,
    reach: 110,
    cap: 4,
    pitch: 0.08,
  },
  reload: {
    prompt: 'Reloading a flintlock gun: a ramrod rattling down the barrel, then the hammer cocked with a click. No music.',
    seconds: 1.5,
    takes: 2,
    volume: 1,
    reach: 25,
    cap: 2,
    pitch: 0.05,
  },
  'bullet-hit': {
    prompt: 'A lead musket ball striking earth and wood: a short thwack with a spray of dirt. One impact only.',
    seconds: 0.5,
    takes: 3,
    volume: 1,
    reach: 45,
    cap: 4,
    pitch: 0.12,
  },
  goat: {
    prompt: 'A startled wild goat bleating once in alarm.',
    seconds: 1,
    takes: 2,
    volume: 1,
    reach: 45,
    cap: 2,
    pitch: 0.1,
  },
  boar: {
    prompt: 'A wild boar snorting and squealing once, angry and startled.',
    seconds: 1,
    takes: 2,
    volume: 1,
    reach: 45,
    cap: 2,
    pitch: 0.1,
  },
  'bandit-shout': {
    prompt: 'A rough pirate bandit shouting an alarm in the distance, a gruff wordless yell to arms.',
    seconds: 1.5,
    takes: 2,
    volume: 1,
    reach: 70,
    cap: 1,
    pitch: 0.05,
  },
  'captain-hurt': {
    prompt: 'A man grunting in pain as he is struck, short and gruff.',
    seconds: 0.6,
    takes: 2,
    volume: 1,
    reach: 0,
    cap: 1,
    pitch: 0.06,
  },
  'blade-clash': {
    prompt: 'Two steel cutlasses clashing hard: a ringing metallic clang. One clash only.',
    seconds: 0.8,
    takes: 3,
    volume: 1,
    reach: 0,
    cap: 3,
    group: 'duel',
    pitch: 0.06,
  },
  parry: {
    prompt: 'A swift sword parry: a bright high steel ring as one blade turns another aside. One parry only.',
    seconds: 0.8,
    takes: 2,
    volume: 1,
    reach: 0,
    cap: 3,
    group: 'duel',
    pitch: 0.05,
  },
  block: {
    prompt: 'A sword blow blocked: a short dull metallic clank of blades. One block only.',
    seconds: 0.6,
    takes: 2,
    volume: 1,
    reach: 0,
    cap: 3,
    group: 'duel',
    pitch: 0.06,
  },
  kick: {
    prompt: 'A heavy boot kick landing on a man\'s body: a dull thump. One kick only.',
    seconds: 0.5,
    takes: 2,
    volume: 1,
    reach: 0,
    cap: 3,
    group: 'duel',
    pitch: 0.08,
  },
  swing: {
    prompt: 'A cutlass swung fast through the air: a short sharp whoosh. One swing only.',
    seconds: 0.5,
    takes: 3,
    volume: 1,
    reach: 0,
    cap: 3,
    group: 'duel',
    pitch: 0.1,
  },
  grunt: {
    prompt: 'A sword fighter grunting with effort as he is hit, short and gruff.',
    seconds: 0.6,
    takes: 3,
    volume: 1,
    reach: 0,
    cap: 3,
    group: 'duel',
    pitch: 0.08,
  },
  'guardian-wail': {
    prompt: 'A ghostly pirate captain rising from a cursed grave: an eerie hollow wail echoing in the night wind. No music.',
    seconds: 4,
    takes: 1,
    volume: 1,
    reach: 0,
    cap: 1,
    pitch: 0.03,
  },
  saw: {
    prompt: 'A two-man pit saw cutting through a log: a few rhythmic rasping strokes. No music.',
    seconds: 2.5,
    takes: 2,
    volume: 1,
    reach: 45,
    cap: 1,
    pitch: 0.05,
  },
  'forge-hammer': {
    prompt: 'A blacksmith hammering hot iron on an anvil: three ringing strikes. No music.',
    seconds: 2,
    takes: 2,
    volume: 1,
    reach: 55,
    cap: 1,
    pitch: 0.05,
  },
  click: {
    prompt: 'A soft wooden click of a button, like a small tap on a ship\'s chart table. Short.',
    seconds: 0.5,
    takes: 2,
    volume: 1,
    reach: 0,
    cap: 2,
    group: 'ui',
    pitch: 0.04,
  },
  coins: {
    prompt: 'A handful of gold coins clinking into a purse. Short.',
    seconds: 0.8,
    takes: 2,
    volume: 1,
    reach: 0,
    cap: 2,
    group: 'ui',
    pitch: 0.06,
  },
  page: {
    prompt: 'A single page of an old parchment book being turned. Short.',
    seconds: 0.8,
    takes: 2,
    volume: 1,
    reach: 0,
    cap: 1,
    group: 'ui',
    pitch: 0.06,
  },
  cant: {
    prompt: 'A short dull wooden knock, a gentle "no" sound for an action that can\'t be done.',
    seconds: 0.5,
    takes: 1,
    volume: 1,
    reach: 0,
    cap: 1,
    group: 'ui',
    pitch: 0.04,
  },
  waves: {
    prompt: 'Calm open-sea waves lapping against a wooden ship\'s hull as she sails, steady and seamless, no wind, no music.',
    seconds: 20,
    takes: 1,
    volume: 1,
    reach: 0,
    cap: 1,
    pitch: 0,
    loop: true,
  },
  timbers: {
    prompt: 'The creaking timbers and ropes of an old wooden sailing ship rolling gently at sea, slow groans and creaks, no music.',
    seconds: 20,
    takes: 1,
    volume: 1,
    reach: 0,
    cap: 1,
    pitch: 0,
    loop: true,
  },
  rigging: {
    prompt: 'Steady wind blowing through a sailing ship\'s rigging and sails, a whistling breeze with canvas fluttering, no music.',
    seconds: 20,
    takes: 1,
    volume: 1,
    reach: 0,
    cap: 1,
    pitch: 0,
    loop: true,
  },
  surf: {
    prompt: 'Gentle surf breaking on a tropical sandy beach, small waves rolling in and washing back, no music.',
    seconds: 20,
    takes: 1,
    volume: 1,
    reach: 0,
    cap: 1,
    pitch: 0,
    loop: true,
  },
  gulls: {
    prompt: 'Seagulls calling over a harbour, distant and occasional, with a soft sea breeze, no music.',
    seconds: 20,
    takes: 1,
    volume: 1,
    reach: 0,
    cap: 1,
    pitch: 0,
    loop: true,
  },
  harbour: {
    prompt: 'The bustle of an 18th-century harbour town: distant murmuring voices, carts, footsteps and a dog far off, no music.',
    seconds: 20,
    takes: 1,
    volume: 1,
    reach: 0,
    cap: 1,
    pitch: 0,
    loop: true,
  },
  campfire: {
    prompt: 'A campfire crackling and popping steadily at night, close up, no music.',
    seconds: 20,
    takes: 1,
    volume: 1,
    reach: 0,
    cap: 1,
    pitch: 0,
    loop: true,
  },
};

/** Match glob results (keys like ".../hull-hit-2.mp3") to sounds, each one's files in take order. Other files are ignored. */
export function filesFrom(paths: Record<string, string>): Map<SfxName, string[]> {
  const found = new Map<SfxName, { take: number; url: string }[]>();
  for (const [path, url] of Object.entries(paths)) {
    const m = /^(.+)-(\d+)\.mp3$/i.exec(path.split('/').pop()!);
    if (!m || !Object.hasOwn(SOUNDS, m[1])) continue;
    const name = m[1] as SfxName;
    const list = found.get(name) ?? [];
    list.push({ take: Number(m[2]), url });
    found.set(name, list);
  }
  const out = new Map<SfxName, string[]>();
  for (const [name, list] of found) out.set(name, list.sort((a, b) => a.take - b.take).map((f) => f.url));
  return out;
}
